import { StyleSheet } from 'react-native';
import { moderateScale, verticalScale, horizontalScale } from '../../utils/responsiveSize';

const styles = StyleSheet.create({
  fullScreenContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    zIndex: 1040,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  inlineContainer: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: verticalScale(32),
    paddingHorizontal: horizontalScale(16),
  },
  contentContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '100%',
  },
  spinnerContainer: {
    position: 'relative',
    width: moderateScale(96),
    height: moderateScale(96),
    marginBottom: verticalScale(24),
    alignSelf: 'center',
  },
  outerStaticRing: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderWidth: moderateScale(4),
    borderColor: '#e5e7eb',
    borderRadius: moderateScale(48),
  },
  spinningRing: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderWidth: moderateScale(4),
    borderColor: '#1E2A4A',
    borderTopColor: 'transparent',
    borderRadius: moderateScale(48),
    width: '100%',
    height: '100%',
  },
  innerSpinningRing: {
    position: 'absolute',
    top: moderateScale(8),
    left: moderateScale(8),
    right: moderateScale(8),
    bottom: moderateScale(8),
    borderWidth: moderateScale(4),
    borderColor: '#F77F6F',
    borderRightColor: 'transparent',
    borderRadius: moderateScale(40),
    width: moderateScale(80),
    height: moderateScale(80),
  },
  centerDotContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerDot: {
    width: moderateScale(12),
    height: moderateScale(12),
    backgroundColor: '#1E2A4A',
    borderRadius: moderateScale(6),
  },
  textContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  loadingText: {
    color: '#1E2A4A',
    fontSize: moderateScale(20),
    fontWeight: '700',
    marginBottom: verticalScale(8),
    textAlign: 'center',
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bounceDot: {
    width: moderateScale(8),
    height: moderateScale(8),
    backgroundColor: '#1E2A4A',
    borderRadius: moderateScale(4),
  },
});

export default styles;

